### PR TITLE
wch linux gcc

### PR DESCRIPTION
**Pull request by 8bitgeek**
I've made sufficient changes such that the configure script and make will now build the openocd binary on Linux, I am using GCC - gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) and issuing the following compiler commands:

```
$ ./configure --enable-wlink --disable-jlink
$ make
$ sudo make install
```

I have not attempted to build on Windows(tm) yet. I will continue to work on the Linux build to get the 'wlink' driver stabilized. 

I am encountering some (looks like minor) issues with the 'wlink' driver, and I will debug those. 

It would be good to do regression testing on some of the other drivers such as st-link and the FTDI drivers. 

There were many coding errors in the wlink code, it was clearly hastily put together, and it does not follow the OpenOCD architecture, meaning, for instance you can't use an st-link (SWD) with a CH32xxx chip (the chip driver and jtag device driver are mushed together). In other words, the end user must always use the `wlink` debugger with CH32xxx chips. 

So those separate parts of the wlink driver code needs to be de-coupled before any of this can be considered for merging into the OpenOCD upstream.

That will be a good bit of work to get the 'wlink' driver in such a good state, and may require some further documentation from WCH. I am evaluating some WCH chips right now, and part of the evaluation criteria is based on being able to build OpenOCD from source and use standalone outside of the WCH IDE.

The reason I mention that, is that, those acceptance criteria will determine whether or not I continue to work on and refine the WDC driver.

For the mean while, this pull request will allow others to at least clone and build, and perhaps begin to also contribute.

### CODE REVIEW

**Comment by 8bitgeek** [comment]
commit #[925a699] allows the WLINK to successfully connect to the CHV103C8. 
I am able to connect GDB to OpenOCD.
Next I will be doing some more testing to see if I can flash and debug, and I'll push any further changes to this branch.

**Comment by newbrain** [comment]
Hi 8bitgeek, and thanks for the hard work you are putting in this!
In full honesty, I never intended to maintain or support this code, I only provided it "as is" as it GPL status was being discussed on EEVBLOG forum.
I also had very few opportunities to experiment with my WCH RISC-V card, I just used the provided IDE on Linux Mint to connect an SPI TFT display - worked as expected.

So, I don't have much time to verify or test your code.

If you agree with this, I would rather keep this repo as an archival copy of what was sent to me by MounRiver.
Since you are putting good effort (thanks again) on this, a possibility could be to point to your fork in the repo description.

What do you think?

**Comment by 8bitgeek** [comment]
> Hi 8bitgeek, and thanks for the hard work you are putting in this! In full honesty, I never intended to maintain or support this code, I only provided it "as is" as it GPL status was being discussed on EEVBLOG forum. I also had very few opportunities to experiment with my WCH RISC-V card, I just used the provided IDE on Linux Mint to connect an SPI TFT display - worked as expected.
> 
> So, I don't have much time to verify or test your code.
> 
> If you agree with this, I would rather keep this repo as an archival copy of what was sent to me by MounRiver. Since you are putting good effort (thanks again) on this, a possibility could be to point to your fork in the repo description.
> 
> What do you think?

No worries! Sounds good!

**Comment by newbrain** [comment]
Added a shout-out to your fork in the repo description.

**Pull request closed without merging**
